version: '3'
services:
  project_manager:
    build: .
    volumes:
      - .:/app
      - ./secrets.json:/app/secrets.json
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
