global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'project_manager'
    static_configs:
      - targets: ['localhost:8000']  # Assuming Project Manager exposes metrics on port 8000
