apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerability-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerability-scanner
  template:
    metadata:
      labels:
        app: vulnerability-scanner
    spec:
      containers:
      - name: vulnerability-scanner
        image: smartcontractanalyzer/vulnerability-scanner:latest
        ports:
        - containerPort: 80
